// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kipnovwqehsnfnbqutrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcG5vdndxZWhzbmZuYnF1dHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDAzNTAsImV4cCI6MjA2MzkxNjM1MH0.UrBOy2-W6rWdDlBEwWh2hrNZBKspyQk_Ipz-xUmYwM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);